name: safe_edge_insets
description: EdgeInsets based on SafeArea.
version: 0.0.4
homepage: https://github.com/gurasan0110/safe_edge_insets

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0